name: C/C++ CI

on:
  push:
    branches: [ final ]
  pull_request:
    branches: [ final ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: MAKE
      run: ./MAKE.sh
